language: scala
scala:
   - 2.11.11
   - 2.11.12
   - 2.12.6
   - 2.12.7
jdk:
  - openjdk8
  - openjdk11

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean scalafmtCheck test:scalafmtCheck compile chimneyJS/test coverage chimneyJVM/test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
